services:
  app:
    image: golang:1.24.4-bookworm
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/go/src/
    working_dir: /go/src
  db:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_vol:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  db_vol:
